# Generated by Django 4.1.7 on 2023-03-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_consumablesbrand_liquidbrand_podbrand_singlebrand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='podbrands/'),
        ),
    ]
