# Generated by Django 4.1.7 on 2023-03-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_liquidbrand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablesbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='podbrands/'),
        ),
        migrations.AddField(
            model_name='podbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='podbrands/'),
        ),
        migrations.AddField(
            model_name='singlebrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='podbrands/'),
        ),
        migrations.AddField(
            model_name='snusbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='podbrands/'),
        ),
    ]
