# Generated by Django 4.1.7 on 2023-03-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liquid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Hotspot', 'Hotspot'), ('Psycho', 'Psycho')], max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
