# Generated by Django 4.1.7 on 2023-03-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquid',
            name='ammount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liquid',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='liquid',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
