# Generated by Django 4.1.7 on 2023-03-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_liquid_ammount_liquid_image_liquid_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liquid',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='liquid',
            name='image',
        ),
    ]
