# Generated by Django 4.1.7 on 2023-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_brand_snus_singleuse_pod_consumables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquid',
            name='brand',
            field=models.CharField(max_length=64),
        ),
    ]
