# Generated by Django 4.1.7 on 2023-03-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_liquid_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquid',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brand'),
        ),
    ]
