# Generated by Django 4.1.7 on 2023-03-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_liquid_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('HotSpot', 'HotSpot'), ('Psycho', 'Psycho')], max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='consumables',
            name='brand',
        ),
        migrations.AlterField(
            model_name='liquid',
            name='brand',
            field=models.CharField(choices=[('HotSpot', 'HotSpot'), ('Psycho', 'Psycho')], max_length=64),
        ),
        migrations.AlterField(
            model_name='pod',
            name='brand',
            field=models.CharField(choices=[('HotSpot', 'HotSpot'), ('Psycho', 'Psycho')], max_length=64),
        ),
        migrations.AlterField(
            model_name='singleuse',
            name='brand',
            field=models.CharField(choices=[('HotSpot', 'HotSpot'), ('Psycho', 'Psycho')], max_length=64),
        ),
        migrations.AlterField(
            model_name='snus',
            name='brand',
            field=models.CharField(choices=[('HotSpot', 'HotSpot'), ('Psycho', 'Psycho')], max_length=64),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Consumables',
        ),
    ]
